#include <SDL.h>
#include <stdio.h>
#include <time.h>
#include <string>
#include "state.h"
#include "mazeoflife.h"
#include "resources.h"
#include "titlestate.h"
#include "htpstate.h"
#include "chlstate.h"
#include "gamestate.h"
